theme_background:
  default: "#{$vincent-background}"
  description:
    en: If you wish to change the default background add the url of the new background above.
dark_background_overlay:
  default: false
  description:
    en: Enable this if you've set a custom background above.
rounded_borders:
  default: false
  description:
    en: Enable rounded borders?
button_text_case:
  default: uppercase
  type: enum
  choices:
    - uppercase
    - capitalize
  description:
    en: What text case should buttons have?
highlight_duration:
  default: 1.5
  min: 0.25
  max: 5
  description:
    en: How long - in seconds - should the highlight last?
